/** Icon to use when no icon specified for domain. */
export const DEFAULT_DOMAIN_ICON_NAME = 'mdi:bookmark';

export const FIXED_DOMAIN_ICONS_NAME = {
  air_quality: 'mdi:air-filter',
  alert: 'mdi:alert',
  calendar: 'mdi:calendar',
  climate: 'mdi:thermostat',
  configurator: 'mdi:cog',
  conversation: 'mdi:microphone-message',
  counter: 'mdi:counter',
  datetime: 'mdi:calendar-clock',
  date: 'mdi:calendar',
  demo: 'mdi:home-assistant',
  google_assistant: 'mdi:google-assistant',
  group: 'mdi:google-circles-communities',
  homeassistant: 'mdi:home-assistant',
  homekit: 'mdi:home-automation',
  image_processing: 'mdi:image-filter-frames',
  input_button: 'mdi:gesture-tap-button',
  input_datetime: 'mdi:calendar-clock',
  input_number: 'mdi:ray-vertex',
  input_select: 'mdi:format-list-bulleted',
  input_text: 'mdi:form-textbox',
  light: 'mdi:lightbulb',
  mailbox: 'mdi:mailbox',
  notify: 'mdi:comment-alert',
  number: 'mdi:ray-vertex',
  persistent_notification: 'mdi:bell',
  plant: 'mdi:Flower',
  proximity: 'mdi:apple-safari',
  remote: 'mdi:remote',
  scene: 'mdi:palette',
  schedule: 'mdi:calendar-clock',
  script: 'mdi:script-text',
  select: 'mdi:format-list-bulleted',
  sensor: 'mdi:eye',
  simple_alarm: 'mdi:bell',
  siren: 'mdi:bullhorn',
  stt: 'mdi:microphone-message',
  text: 'mdi:form-textbox',
  time: 'mdi:clock',
  timer: 'mdi:timer-outline',
  tts: 'mdi:speaker-message',
  updater: 'mdi:cloud-upload',
  vacuum: 'mdi:robot-vacuum',
  zone: 'mdi:map-marker-radius',
};

export const FIXED_DEVICE_CLASS_ICONS_NAME = {
  apparent_power: 'mdi:flash',
  aqi: 'mdi:air-filter',
  atmospheric_pressure: 'mdi:thermometer-lines',
  // battery: 'mdi:Battery, => not included by design since `sensorIcon()` will dynamically determine the icon
  carbon_dioxide: 'mdi:molecule-co2',
  carbon_monoxide: 'mdi:molecule-co',
  current: 'mdi:current-ac',
  data_rate: 'mdi:transmission-tower',
  data_size: 'mdi:database',
  date: 'mdi:calendar',
  distance: 'mdi:arrow-left-right',
  duration: 'mdi:progress-clock',
  energy: 'mdi:lightning-bolt',
  frequency: 'mdi:sine-wave',
  gas: 'mdi:meter-gas',
  humidity: 'mdi:water-percent',
  illuminance: 'mdi:brightness-5',
  irradiance: 'mdi:sun-wireless',
  moisture: 'mdi:water-percent',
  monetary: 'mdi:cash',
  nitrogen_dioxide: 'mdi:molecule',
  nitrogen_monoxide: 'mdi:molecule',
  nitrous_oxide: 'mdi:molecule',
  ozone: 'mdi:molecule',
  pm1: 'mdi:molecule',
  pm10: 'mdi:molecule',
  pm25: 'mdi:molecule',
  power: 'mdi:flash',
  power_factor: 'mdi:angle-acute',
  precipitation: 'mdi:weather-rainy',
  precipitation_intensity: 'mdi:weather-pouring',
  pressure: 'mdi:gauge',
  reactive_power: 'mdi:flash',
  signal_strength: 'mdi:wifi',
  sound_pressure: 'mdi:ear-hearing',
  speed: 'mdi:speedometer',
  sulphur_dioxide: 'mdi:molecule',
  temperature: 'mdi:thermometer',
  timestamp: 'mdi:clock',
  volatile_organic_compounds: 'mdi:molecule',
  volatile_organic_compounds_parts: 'mdi:molecule',
  voltage: 'mdi:sine-wave',
  volume: 'mdi:car-coolant-level',
  water: 'mdi:water',
  weight: 'mdi:weight',
  wind_speed: 'mdi:weather-windy',
};
